### ISSUE TITLE
Banks界面显示有不一致的地方

### ISSUE THREAD

**Issue by moeray** [G-Ricky/gctf#8]
在没有题目的bank中顶端菜单条,比有题目的bank中顶端菜单条要显得宽,以及More的页面也会显得宽,是否应该修改成一致的宽高?

**Comment by moeray** [comment]
不止banks会出现,其他的例如Ranking也会

**Comment by G-Ricky** [comment]
目前不清楚原因，可能是框架对响应式的支持不是很好
